/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp manifest.xml -i data/PresetRule.h --adaptor ServerAdaptor --proxy ClientProxy
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "ClientProxy.h"

/*
 * Implementation of interface class OrgAudioforgeJamesdspGuiInterface
 */

OrgAudioforgeJamesdspGuiInterface::OrgAudioforgeJamesdspGuiInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgAudioforgeJamesdspGuiInterface::~OrgAudioforgeJamesdspGuiInterface()
{
}

/*
 * Implementation of interface class OrgAudioforgeJamesdspServiceInterface
 */

OrgAudioforgeJamesdspServiceInterface::OrgAudioforgeJamesdspServiceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgAudioforgeJamesdspServiceInterface::~OrgAudioforgeJamesdspServiceInterface()
{
}

